### ISSUE TITLE
PgBouncer Read Distribution across Standby Nodes

### ISSUE THREAD

**Issue by spron-in** [percona/roadmap#96]
**Which operator(s) is this request for?**
- [x] Percona Operator for PostgreSQL (PG)

**Why this matters**
PostgreSQL's ability to scale reads across multiple standby nodes is one of its most valuable capabilities for high-traffic workloads, but without connection pooling on the replica path, that scalability comes at the cost of connection overhead that quickly becomes a bottleneck at scale. By extending PgBouncer to pool connections to standby nodes, the Percona Operator for PostgreSQL lets organizations fully utilize their replica fleet for read-heavy applications without any additional infrastructure or manual configuration. For teams evaluating Percona for production Kubernetes deployments, this closes a meaningful gap between what the cluster can do and what the operator makes accessible out of the box.

<img width="960" height="480" alt="Image" src="https://github.com/user-attachments/assets/cf5dce44-ab7e-410f-b8a0-d6ff2f78cf85" />

**Jira:** https://jira.percona.com/browse/K8SPG-154

---

### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, as they generate noise and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by hors** [comment]
The operator already allows you to configure pgBouncer. So if we want separate read/write pools, we can do the following:
```
      config:
        databases:
          "*": "host=cluster1-primary port=5432"
          mydb: "host=cluster1-primary port=5432"
          mydb_ro: "host=cluster1-replicas port=5432 dbname=mydb"
```
